[build]
  command = "npm run build"
  publish = "dist/app"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "DENY"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
