import { hashValue } from '../../domain/src/hash.ts';

/**
 * Builds a CalTopo-importable GeoJSON search map from initial incident details:
 * range rings, dispersion wedges and a first cut of unassigned segments, in the
 * numbered folders of the BYK search map template.
 *
 * Ring distances and dispersion angles are inputs with a named source. This
 * module holds no behavioural statistics of its own.
 *
 * Geometry matches the BYK examples: rings are closed LineStrings of 73 points
 * at 5° steps starting due north; wedges are polygons from the planning point
 * out to the ring of the same percentile.
 */
export const GENERATOR_VERSION = 'search-map@0.1.0';
export const MODE_NOTE = 'Generated by the Lost-Person Probability Mapper in training/research mode. Not approved for operational use.';

/** Folder titles exactly as in the BYK search map template. */
export const TEMPLATE_FOLDERS = [
  '1 - Important Points',
  '2 - Clues',
  '3 - Range rings and Dispersion angles',
  '4 - Op 1 Air Tracks',
  '5 - OP 1 Ground Tracks',
  '6 - Air Assignments',
  '7 - Ground Assignments',
  '8 - Unassigned Segments',
] as const;

/**
 * Folder ids from the BYK template. Real maps built from the template keep them,
 * so features imported with these ids land in the template's own folders.
 */
export const TEMPLATE_FOLDER_IDS: Record<(typeof TEMPLATE_FOLDERS)[number], string> = {
  '1 - Important Points': 'bfae8b57-66c1-4f19-b300-fa67d2dc0cf1',
  '2 - Clues': '49a8bc63-d833-4caa-a4b1-34a287dde302',
  '3 - Range rings and Dispersion angles': '296a4f7d-82c4-48b7-944d-d3fd610e4aeb',
  '4 - Op 1 Air Tracks': '9dbbeff9-63bd-4eea-84d6-007fcdb1300d',
  '5 - OP 1 Ground Tracks': '2105ac92-0106-4225-a9fb-ee132565047a',
  '6 - Air Assignments': 'dab108f2-73da-4e1c-849f-f42aef09155b',
  '7 - Ground Assignments': '233a79cd-fd46-4a51-a1a1-ecc51605a192',
  '8 - Unassigned Segments': '458ef425-d0f7-45f3-9712-d1d1008d9f5e',
};

/** The template opens with these folders collapsed out of view; the assignment folders stay shown. */
const FOLDER_VISIBLE = new Set(['6 - Air Assignments', '7 - Ground Assignments', '8 - Unassigned Segments']);

export interface LngLat {
  lng: number;
  lat: number;
}

export interface SearchMapInput {
  /** Short case label for titles. No names: the generator refuses anything that looks like one. */
  label: string;
  planningPoint: LngLat & { kind: 'IPP' | 'LKP' | 'PLS' };
  /** Direction of travel in degrees from true north, when known. Wedges need it. */
  travelBearingDeg?: number;
  /** Activity category the ring source was looked up for, e.g. "hiker". Recorded on the planning point. */
  subjectCategory?: string;
  rings: Array<{ percent: number; distanceKm: number }>;
  /** Where the ring distances come from, e.g. a named table and subject category. Required. */
  ringSource: string;
  dispersion?: Array<{ percent: number; angleDeg: number }>;
  dispersionSource?: string;
  segments?: { sectors: number; outToPercent: number };
}

export interface CaltopoFeature {
  type: 'Feature';
  id: string;
  geometry: null | { type: 'Point'; coordinates: number[] } | { type: 'LineString'; coordinates: number[][] } | { type: 'Polygon'; coordinates: number[][][] };
  properties: Record<string, unknown>;
}

export interface SearchMap {
  type: 'FeatureCollection';
  features: CaltopoFeature[];
}

const EARTH_RADIUS_M = 6_371_008.8;
const STEP_DEG = 5;
const rad = (d: number) => (d * Math.PI) / 180;
const deg = (r: number) => (r * 180) / Math.PI;
const round = (v: number) => Math.round(v * 1e7) / 1e7;

/** Point at `distanceM` along `bearingDeg` from `from`, on a sphere. */
export function destination(from: LngLat, bearingDeg: number, distanceM: number): LngLat {
  const d = distanceM / EARTH_RADIUS_M;
  const b = rad(bearingDeg);
  const la1 = rad(from.lat);
  const lo1 = rad(from.lng);
  const la2 = Math.asin(Math.sin(la1) * Math.cos(d) + Math.cos(la1) * Math.sin(d) * Math.cos(b));
  const lo2 = lo1 + Math.atan2(Math.sin(b) * Math.sin(d) * Math.cos(la1), Math.cos(d) - Math.sin(la1) * Math.sin(la2));
  return { lng: ((deg(lo2) + 540) % 360) - 180, lat: deg(la2) };
}

/** Great-circle distance in metres. */
export function distanceM(a: LngLat, b: LngLat): number {
  const dla = rad(b.lat - a.lat);
  const dlo = rad(b.lng - a.lng);
  const h = Math.sin(dla / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dlo / 2) ** 2;
  return 2 * EARTH_RADIUS_M * Math.asin(Math.sqrt(h));
}

/** CalTopo's own 4-tuple: longitude, latitude, elevation and time, the last two 0 when unknown. */
const coord = (p: LngLat) => [round(p.lng), round(p.lat), 0, 0];

/** Points along an arc from `fromDeg` clockwise to `toDeg`, at most STEP_DEG apart, both ends included. */
function arc(centre: LngLat, radiusM: number, fromDeg: number, toDeg: number): number[][] {
  const span = toDeg - fromDeg;
  const n = Math.max(1, Math.ceil(span / STEP_DEG));
  return Array.from({ length: n + 1 }, (_, i) => coord(destination(centre, fromDeg + (span * i) / n, radiusM)));
}

/** Closed ring of 73 points (5° steps from due north), as in the BYK examples. */
export function ringLine(centre: LngLat, radiusM: number): number[][] {
  const pts = arc(centre, radiusM, 0, 360);
  pts[pts.length - 1] = pts[0]!;
  return pts;
}

/** Wedge from the planning point, `angleDeg` wide, centred on `bearingDeg`, out to `radiusM`. */
export function wedgePolygon(centre: LngLat, bearingDeg: number, angleDeg: number, radiusM: number): number[][] {
  const c = coord(centre);
  return [c, ...arc(centre, radiusM, bearingDeg - angleDeg / 2, bearingDeg + angleDeg / 2), c];
}

/** Band between two radii, between two bearings. An inner radius of 0 gives a wedge. */
export function sectorPolygon(centre: LngLat, innerM: number, outerM: number, fromDeg: number, toDeg: number): number[][] {
  const outer = arc(centre, outerM, fromDeg, toDeg);
  const inner = innerM > 0 ? arc(centre, innerM, fromDeg, toDeg).reverse() : [coord(centre)];
  return [...outer, ...inner, outer[0]!];
}

const COMPASS = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];
function sectorName(i: number, sectors: number): string {
  if (sectors === 8) return COMPASS[i]!;
  if (sectors === 4) return ['N', 'E', 'S', 'W'][i]!;
  return `S${i + 1}`;
}

/** Like the examples: "3.65 km", "18.3 km", "1 km". */
const fmtKm = (km: number) => `${Number(km.toFixed(km < 10 ? 2 : 1))} km`;

/** Problems with the input; empty when it can be generated. */
export function validateSearchMapInput(input: SearchMapInput): string[] {
  const errs: string[] = [];
  const { lat, lng } = input.planningPoint;
  if (!(lat >= -90 && lat <= 90 && lng >= -180 && lng <= 180)) errs.push('planning point must be a valid latitude and longitude');
  if (!input.label.trim() || input.label.length > 40) errs.push('label must be 1 to 40 characters');
  // A case label is a place and date, never a person: refuse two capitalised words in a row or digits that look like a phone number.
  if (/\b[A-Z][a-z]+\s+[A-Z][a-z]+\b/.test(input.label) && !/(Lake|Canyon|Creek|River|Mountain|Mount|Peak|Pass|Valley|Trail|Glacier|Falls|Ridge|Park)\b/.test(input.label))
    errs.push('label looks like a person\'s name; use a place and date instead');
  if (input.subjectCategory !== undefined && !/^[a-z][a-z -]{0,29}$/.test(input.subjectCategory))
    errs.push('subject category must be a short lower-case activity word such as hiker');
  if (/\d{3}[\s.-]?\d{3}[\s.-]?\d{4}/.test(input.label)) errs.push('label looks like it contains a phone number');
  if (!input.ringSource.trim()) errs.push('ring source is required: name the table and subject category the distances come from');
  if (!input.rings.length) errs.push('at least one range ring is required');
  input.rings.forEach((r, i) => {
    if (!(r.percent > 0 && r.percent < 100)) errs.push(`ring ${i + 1}: percent must be between 0 and 100`);
    if (!(r.distanceKm > 0 && r.distanceKm <= 200)) errs.push(`ring ${i + 1}: distance must be between 0 and 200 km`);
    const prev = input.rings[i - 1];
    if (prev && !(r.percent > prev.percent && r.distanceKm > prev.distanceKm)) errs.push(`ring ${i + 1}: percent and distance must both increase`);
  });
  const disp = input.dispersion ?? [];
  if (disp.length) {
    if (!(input.dispersionSource ?? '').trim()) errs.push('dispersion source is required when dispersion angles are given');
    if (input.travelBearingDeg === undefined || !(input.travelBearingDeg >= 0 && input.travelBearingDeg < 360)) errs.push('dispersion angles need a direction of travel between 0 and 359°');
    disp.forEach((d, i) => {
      if (!(d.angleDeg > 0 && d.angleDeg <= 360)) errs.push(`dispersion ${i + 1}: angle must be between 0 and 360°`);
      if (!input.rings.some((r) => r.percent === d.percent)) errs.push(`dispersion ${i + 1}: there is no ${d.percent}% ring to set its length`);
    });
  }
  const seg = input.segments;
  if (seg) {
    if (![4, 8, 12, 16].includes(seg.sectors)) errs.push('segments: sectors must be 4, 8, 12 or 16');
    if (!input.rings.some((r) => r.percent === seg.outToPercent)) errs.push(`segments: there is no ${seg.outToPercent}% ring to stop at`);
  }
  return errs;
}

/** Deterministic id from the input and a feature key, so the same input gives the same file. */
function idFor(seed: string, key: string): string {
  const h = hashValue(`${seed}:${key}`);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

const RING_STYLE = { stroke: '#00FF00', 'stroke-width': 4, 'stroke-opacity': 0.8, pattern: 'solid' };
const WEDGE_STYLE = { stroke: '#FFAA00', 'stroke-width': 2, 'stroke-opacity': 1, pattern: 'solid', fill: '#FFAA00', 'fill-opacity': 0.15 };
const SEGMENT_STYLE = { stroke: '#FF0000', 'stroke-width': 2, 'stroke-opacity': 1, pattern: 'solid', fill: '#FF0000', 'fill-opacity': 0.05 };

/** Builds the CalTopo FeatureCollection. Throws with the validation problems if the input is not usable. */
export function buildSearchMap(input: SearchMapInput): SearchMap {
  const errs = validateSearchMapInput(input);
  if (errs.length) throw new Error(errs.join('; '));
  const seed = hashValue(input);
  const folderIds = TEMPLATE_FOLDER_IDS;
  const features: CaltopoFeature[] = TEMPLATE_FOLDERS.map((title) => ({
    type: 'Feature',
    id: folderIds[title],
    geometry: null,
    properties: { class: 'Folder', title, visible: FOLDER_VISIBLE.has(title), labelVisible: true },
  }));
  const pp = input.planningPoint;
  const note = (extra: string) => `${MODE_NOTE} ${extra} (${GENERATOR_VERSION})`;

  features.push({
    type: 'Feature',
    id: idFor(seed, 'planning-point'),
    geometry: { type: 'Point', coordinates: coord(pp) },
    properties: { class: 'Marker', title: pp.kind, description: note(`Planning point for the rings below. Case: ${input.label}.${input.subjectCategory ? ` Subject category: ${input.subjectCategory}.` : ''}`), 'marker-symbol': 'cp', 'marker-color': '#ff0000', 'marker-size': 1, 'marker-rotation': 0, folderId: folderIds['1 - Important Points'] },
  });

  for (const r of input.rings) {
    features.push({
      type: 'Feature',
      id: idFor(seed, `ring:${r.percent}`),
      geometry: { type: 'LineString', coordinates: ringLine(pp, r.distanceKm * 1000) },
      properties: { class: 'Shape', title: `${r.percent}% ${fmtKm(r.distanceKm)}`, description: note(`Ring distance source: ${input.ringSource}.`), ...RING_STYLE, folderId: folderIds['3 - Range rings and Dispersion angles'] },
    });
  }

  for (const d of input.dispersion ?? []) {
    const ring = input.rings.find((r) => r.percent === d.percent)!;
    features.push({
      type: 'Feature',
      id: idFor(seed, `wedge:${d.percent}`),
      geometry: { type: 'Polygon', coordinates: [wedgePolygon(pp, input.travelBearingDeg!, d.angleDeg, ring.distanceKm * 1000)] },
      properties: { class: 'Shape', title: `${d.percent}% dispersion ${d.angleDeg}°`, description: note(`Dispersion angle source: ${input.dispersionSource}. Centred on a direction of travel of ${input.travelBearingDeg}°.`), ...WEDGE_STYLE, folderId: folderIds['3 - Range rings and Dispersion angles'] },
    });
  }

  if (input.segments) {
    const { sectors, outToPercent } = input.segments;
    const bands = input.rings.filter((r) => r.percent <= outToPercent);
    const width = 360 / sectors;
    bands.forEach((r, b) => {
      const inner = b === 0 ? 0 : bands[b - 1]!.distanceKm * 1000;
      for (let s = 0; s < sectors; s++) {
        const name = `R${b + 1}-${sectorName(s, sectors)}`;
        features.push({
          type: 'Feature',
          id: idFor(seed, `segment:${name}`),
          geometry: { type: 'Polygon', coordinates: [sectorPolygon(pp, inner, r.distanceKm * 1000, s * width - width / 2, s * width + width / 2)] },
          properties: {
            class: 'Assignment',
            title: name,
            letter: name,
            status: 'DRAFT',
            resourceType: 'GROUND',
            description: note(`First-cut segment: ring band ${b + 1} (to the ${r.percent}% ring), ${sectorName(s, sectors)} sector. Adjust to terrain before assigning.`),
            ...SEGMENT_STYLE,
            folderId: folderIds['8 - Unassigned Segments'],
          },
        });
      }
    });
  }

  return { type: 'FeatureCollection', features };
}

/** File name with the mode in it, as the brief requires for exports. */
export function searchMapFileName(input: SearchMapInput): string {
  const safe = input.label.replace(/[^\w-]+/g, '_').replace(/_+/g, '_').slice(0, 40);
  return `${safe}_TRAINING_search_map.json`;
}
